# Generated by Django 5.0.7 on 2024-07-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_institution_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('organizacja porządkowa', 'organizacja porządkowa'), ('zbiórka lokalna', 'zbiórka lokalna'), ('fundacja', 'fundacja')], default='fundacja', max_length=100),
        ),
    ]
