# Generated by Django 5.0.7 on 2024-07-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_donation_pick_up_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_comment',
            field=models.TextField(default='brak komentarza', null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('organizacja porządkowa', 'organizacja porządkowa'), ('fundacja', 'fundacja'), ('zbiórka lokalna', 'zbiórka lokalna')], default='fundacja', max_length=100),
        ),
    ]
